### ISSUE TITLE
Transformer mask

### ISSUE THREAD

**Issue by zhang-potato** [Daikon-Sun/AdjustAutocorrelation#3]
If my transformer code have mask operation,should I also have a rho operation for it

**Comment by Daikon-Sun** [comment]
No need. Just follow the formulation in the paper.

**Comment by zhang-potato** [comment]
谢谢，如果我预测的是未来24小时的数据，pred为三维的（32，24，6），那么pred += rho * x[:, -1]这一步，我是不是需要将24小时的预测值都加上相同的x[:, -1]

**Comment by Daikon-Sun** [comment]
不是，現在的算法只支援autoregressive generation，所以只能一步一步預測

**Comment by zhang-potato** [comment]
好的，谢谢您
